#! /bin/sh

## bootstrap 
echo "$HOME" > /tmp/whereami
nm-applet &
nitrogen --restore &
.config/polybar/launch.sh &
picom --experimental-backends &

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            12
bspc config focused_border_color  '#00BCD4'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
