
(setq fancy-splash-image "~/.config/doom/logo.png")
(setq doom-font (font-spec :family "Ubuntu Mono" :size 20))
(setq doom-theme 'doom-dracula)
(setq org-directory "~/org/")
(setq display-line-numbers-type 'relative)
(setq confirm-kill-emacs nil)
(setq initial-frame-alist '((left . 0) (fullscreen . maximized)))
(setq doom-treemacs-use-generic-icons nil)
(setq ranger-override-dired-mode t)
